version: '3.8'
services:
  flask-payment-app:
    build: .
    ports:
      - "5002:5000"
    env_file:
      - .env
    environment:
      - FLASK_ENV=${FLASK_ENV:-production}
      - TZ=${TZ:-Europe/London}
      - ST_USERNAME=${ST_USERNAME}
      - ST_PASSWORD=${ST_PASSWORD}
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
    volumes:
      - payment-logs:/app/logs
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro      
    restart: unless-stopped
    container_name: payment-app

volumes:
  payment-logs:
    external: true